# Generated by Django 3.1.7 on 2024-02-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
