# Generated by Django 3.1.7 on 2024-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20240205_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(null=True, related_name='categories', to='e_commerce.Item'),
        ),
    ]
